In [1]:
%load_ext autoreload
%autoreload 2
from objects import convex_polygon
import jax.numpy as jnp

In [2]:
square = convex_polygon([[0,0],[0,1],[1,0],[1,1]])

In [3]:
square.normals_0

DeviceArray([[-1.,  0.],
             [ 0., -1.],
             [ 1.,  0.],
             [ 0.,  1.]], dtype=float32)

In [4]:
com = jnp.array([0.,0.])
square.get_vertices_normals_proj_jax(com,jnp.array(0.0))

(DeviceArray([[-0.5, -0.5],
              [ 0.5, -0.5],
              [ 0.5,  0.5],
              [-0.5,  0.5]], dtype=float32),
 DeviceArray([[-1.,  0.],
              [ 0., -1.],
              [ 1.,  0.],
              [ 0.,  1.]], dtype=float32),
 DeviceArray([0.5, 0.5, 0.5, 0.5], dtype=float32))

In [5]:
positions = jnp.array([[0.4,0.],[0.,0.4],[-0.4,0.]])
positions + square.get_min_particle_push_vector(com, 0.0, positions)

DeviceArray([[ 0.50009763,  0.        ],
             [ 0.        ,  0.50009763],
             [-0.50009763,  0.        ]], dtype=float32)