In [15]:
%load_ext autoreload
%autoreload 2
from objects import vertices_to_polygon
import jax.numpy as jnp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
square = vertices_to_polygon([[0,0],[0,1],[1,0],[1,1]])

In [17]:
square.normals_0

DeviceArray([[-1.,  0.],
             [ 0., -1.],
             [ 1.,  0.],
             [ 0.,  1.]], dtype=float32)

In [20]:
com = jnp.array([0.,0.])
square.get_vertices_normals_proj_jax(com,jnp.array(0.0))

(DeviceArray([[-0.5, -0.5],
              [ 0.5, -0.5],
              [ 0.5,  0.5],
              [-0.5,  0.5]], dtype=float32),
 DeviceArray([[-1.,  0.],
              [ 0., -1.],
              [ 1.,  0.],
              [ 0.,  1.]], dtype=float32),
 DeviceArray([0.5, 0.5, 0.5, 0.5], dtype=float32))