In [43]:
%load_ext autoreload
%autoreload 2
from objects import convex_polygon
import jax.numpy as jnp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [44]:
square = convex_polygon([[0,0],[0,1],[1,0],[1,1]])
square.rot_gamma = 1.

In [45]:
square.normals_0

DeviceArray([[-1.,  0.],
             [ 0., -1.],
             [ 1.,  0.],
             [ 0.,  1.]], dtype=float32)

In [46]:
com = jnp.array([0.,0.])
square.get_vertices_normals_proj_jax(com,jnp.array(0.0))

(DeviceArray([[-0.5, -0.5],
              [ 0.5, -0.5],
              [ 0.5,  0.5],
              [-0.5,  0.5]], dtype=float32),
 DeviceArray([[-1.,  0.],
              [ 0., -1.],
              [ 1.,  0.],
              [ 0.,  1.]], dtype=float32),
 DeviceArray([0.5, 0.5, 0.5, 0.5], dtype=float32))

In [47]:
positions = jnp.array([[0.4,0.1],[0.,0.6],[-0.4,-0.1]])
mpv = square.get_min_particle_push_vector(com, 0.0, positions)
positions + mpv

DeviceArray([[ 0.50009763,  0.1       ],
             [ 0.        ,  0.6       ],
             [-0.50009763, -0.1       ]], dtype=float32)

In [48]:
square.get_rotation_from_wall_particle_interaction(com, positions, mpv, 1)

DeviceArray(0.02001953, dtype=float32)